version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Map Nginx server to port 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DATABASE_URL: "postgresql://admin:secretpassword@db:5432/foodbot"

  db:
    build:
      context: ../database
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
