# Use the official PostgreSQL image
FROM postgres:15

# Set environment variables for database (use in docker-compose)
ENV POSTGRES_DB=foodbot
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=secretpassword

# Expose the PostgreSQL default port
EXPOSE 5432
